# Generated by Django 5.1.3 on 2024-11-10 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_user_comment_follow_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
